name: Build & (Optional) Dockerize Project

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package --batch-mode

      - name: Archive JAR
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: springboot-app
          path: target/*.jar

  # Optional Docker image build step
  docker-build:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t star-agile-insurance:latest .
          
    
